CREATE TABLE pedidos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  cliente_id INTEGER NOT NULL,
  fecha_pedido DATETIME DEFAULT CURRENT_TIMESTAMP,
  estado_pedido TEXT NOT NULL,
  FOREIGN KEY (cliente_id) REFERENCES clientes(id)
);